version: "3.8"

services:
  yolo-client:
    image: hesbonangwenyi606/yolo-client:v1.0.0
    container_name: yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - app-net

  yolo-backend:
    image: hesbonangwenyi606/yolo-backend:v1.0.0
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
