- name: Create Docker network for app
  community.docker.docker_network:
    name: app-net
    state: present

- name: Run MongoDB container
  community.docker.docker_container:
    name: mongodb
    image: mongo:latest
    state: started
    restart_policy: always
    recreate: false
    ports:
      - "27017:27017"
    networks:
      - name: app-net
  tags:
    - database
    - backend
- name: Create Docker network
  community.docker.docker_network:
    name: app-net
    state: present

- name: Create Docker network
  community.docker.docker_network:
    name: app-net
    state: present

- name: Create Docker network
  community.docker.docker_network:
    name: app-net
    state: present

- name: Run MongoDB Container
  community.docker.docker_container:
    name: mongodb
    image: mongo:latest
    state: started
    restart_policy: always
    networks:
      - name: app-net
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

