---
- name: Provision Docker and Deploy App
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker packages
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python (system-wide)
      pip:
        name: docker
        executable: /usr/bin/pip3

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Copy docker-compose.yml to VM
      copy:
        src: ./docker-compose.yml
        dest: /home/vagrant/docker-compose.yml
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Copy app directory to VM
      copy:
        src: ./app/
        dest: /home/vagrant/app/
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Run docker-compose up
      become: false
      shell: docker compose -f /home/vagrant/docker-compose.yml up -d
      args:
        chdir: /home/vagrant
